# Generated by Django 5.2.7 on 2025-10-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0001_initial'),
        ('escolas', '0001_initial'),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='escolas.turma'),
        ),
        migrations.AddField(
            model_name='caderno',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='caderno',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria'),
        ),
        migrations.AddField(
            model_name='cadernoquestao',
            name='caderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.caderno'),
        ),
        migrations.AddField(
            model_name='cadernoquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.questao'),
        ),
        migrations.AddField(
            model_name='caderno',
            name='questoes',
            field=models.ManyToManyField(through='avaliacoes.CadernoQuestao', to='itens.questao'),
        ),
        migrations.AddField(
            model_name='provaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.aluno'),
        ),
        migrations.AddField(
            model_name='provaaluno',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='provaaluno',
            name='caderno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacoes.caderno'),
        ),
        migrations.AddField(
            model_name='provaaluno',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria'),
        ),
        migrations.AlterUniqueTogether(
            name='cadernoquestao',
            unique_together={('caderno', 'questao')},
        ),
    ]
