# Generated by Django 5.1.13 on 2025-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='habilitar_correcao_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='liberada_para_professores',
            field=models.BooleanField(default=False),
        ),
    ]
