# Generated by Django 5.1.13 on 2025-11-02 16:37

from django.db import migrations


def _normalize_payload(instance, include_prova_id=True):
    payload = getattr(instance, 'qr_payload', {}) or {}
    if not isinstance(payload, dict):
        payload = {}
    changed = False

    if payload.get('aluno_id') != instance.aluno_id:
        payload['aluno_id'] = instance.aluno_id
        changed = True
    if payload.get('aluno_nome') != getattr(instance.aluno, 'nome', None):
        aluno_nome = getattr(instance.aluno, 'nome', None)
        if aluno_nome:
            payload['aluno_nome'] = aluno_nome
            changed = True
    if payload.get('avaliacao_id') != instance.avaliacao_id:
        payload['avaliacao_id'] = instance.avaliacao_id
        changed = True
    if payload.get('avaliacao_titulo') != getattr(instance.avaliacao, 'titulo', None):
        titulo = getattr(instance.avaliacao, 'titulo', None)
        if titulo:
            payload['avaliacao_titulo'] = titulo
            changed = True
    caderno_id = instance.caderno_id
    if payload.get('caderno_id') != caderno_id:
        if caderno_id is not None:
            payload['caderno_id'] = caderno_id
        elif 'caderno_id' in payload:
            payload.pop('caderno_id')
        changed = True
    if include_prova_id:
        if payload.get('prova_id') != instance.id:
            payload['prova_id'] = instance.id
            changed = True
    return payload, changed


def forward(apps, schema_editor):
    ProvaAluno = apps.get_model('avaliacoes', 'ProvaAluno')
    for prova in ProvaAluno.objects.select_related('aluno', 'avaliacao', 'caderno').all():
        payload, changed = _normalize_payload(prova, include_prova_id=True)
        if changed:
            ProvaAluno.objects.filter(pk=prova.pk).update(qr_payload=payload)


def backward(apps, schema_editor):
    ProvaAluno = apps.get_model('avaliacoes', 'ProvaAluno')
    for prova in ProvaAluno.objects.all():
        payload = getattr(prova, 'qr_payload', {}) or {}
        if isinstance(payload, dict) and 'prova_id' in payload:
            payload = dict(payload)
            payload.pop('prova_id', None)
            ProvaAluno.objects.filter(pk=prova.pk).update(qr_payload=payload)


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_avaliacao_habilitar_correcao_qr_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
