# Generated by Django 5.2.7 on 2025-10-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_inep', models.CharField(blank=True, max_length=20)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=20)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.escola')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.turma')),
            ],
        ),
    ]
