# Generated by Django 5.2.7 on 2025-10-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_correta', models.CharField(max_length=1)),
                ('caderno_questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.cadernoquestao')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('correta', models.BooleanField(null=True)),
                ('caderno_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.cadernoquestao')),
                ('prova_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.provaaluno')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria')),
            ],
            options={
                'unique_together': {('prova_aluno', 'caderno_questao')},
            },
        ),
    ]
